package com.backstage.pojo;

public class Field {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIELD.FIELDID
     *
     * @mbg.generated Sat Jan 22 23:28:26 CST 2022
     */
    private Integer fieldid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FIELD.FIELDNAME
     *
     * @mbg.generated Sat Jan 22 23:28:26 CST 2022
     */
    private String fieldname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIELD.FIELDID
     *
     * @return the value of FIELD.FIELDID
     *
     * @mbg.generated Sat Jan 22 23:28:26 CST 2022
     */
    public Integer getFieldid() {
        return fieldid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIELD.FIELDID
     *
     * @param fieldid the value for FIELD.FIELDID
     *
     * @mbg.generated Sat Jan 22 23:28:26 CST 2022
     */
    public void setFieldid(Integer fieldid) {
        this.fieldid = fieldid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FIELD.FIELDNAME
     *
     * @return the value of FIELD.FIELDNAME
     *
     * @mbg.generated Sat Jan 22 23:28:26 CST 2022
     */
    public String getFieldname() {
        return fieldname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FIELD.FIELDNAME
     *
     * @param fieldname the value for FIELD.FIELDNAME
     *
     * @mbg.generated Sat Jan 22 23:28:26 CST 2022
     */
    public void setFieldname(String fieldname) {
        this.fieldname = fieldname == null ? null : fieldname.trim();
    }
}