package com.backstage.pojo;

public class Grade {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GRADE.GRADE
     *
     * @mbg.generated Sat Jan 22 23:28:26 CST 2022
     */
    private Integer grade;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GRADE.LOWPOINT
     *
     * @mbg.generated Sat Jan 22 23:28:26 CST 2022
     */
    private Integer lowpoint;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GRADE.HIGHPOINT
     *
     * @mbg.generated Sat Jan 22 23:28:26 CST 2022
     */
    private Integer highpoint;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GRADE.GRADE
     *
     * @return the value of GRADE.GRADE
     *
     * @mbg.generated Sat Jan 22 23:28:26 CST 2022
     */
    public Integer getGrade() {
        return grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GRADE.GRADE
     *
     * @param grade the value for GRADE.GRADE
     *
     * @mbg.generated Sat Jan 22 23:28:26 CST 2022
     */
    public void setGrade(Integer grade) {
        this.grade = grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GRADE.LOWPOINT
     *
     * @return the value of GRADE.LOWPOINT
     *
     * @mbg.generated Sat Jan 22 23:28:26 CST 2022
     */
    public Integer getLowpoint() {
        return lowpoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GRADE.LOWPOINT
     *
     * @param lowpoint the value for GRADE.LOWPOINT
     *
     * @mbg.generated Sat Jan 22 23:28:26 CST 2022
     */
    public void setLowpoint(Integer lowpoint) {
        this.lowpoint = lowpoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GRADE.HIGHPOINT
     *
     * @return the value of GRADE.HIGHPOINT
     *
     * @mbg.generated Sat Jan 22 23:28:26 CST 2022
     */
    public Integer getHighpoint() {
        return highpoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GRADE.HIGHPOINT
     *
     * @param highpoint the value for GRADE.HIGHPOINT
     *
     * @mbg.generated Sat Jan 22 23:28:26 CST 2022
     */
    public void setHighpoint(Integer highpoint) {
        this.highpoint = highpoint;
    }
}