package com.backstage.pojo;

import java.util.Date;

public class History {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HISTORY.USERNAME
     *
     * @mbg.generated Tue Jan 25 16:23:47 CST 2022
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HISTORY.VIDEOID
     *
     * @mbg.generated Tue Jan 25 16:23:47 CST 2022
     */
    private Integer videoid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HISTORY.TIME
     *
     * @mbg.generated Tue Jan 25 16:23:47 CST 2022
     */
    private Date time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column HISTORY.HIS
     *
     * @mbg.generated Tue Jan 25 16:23:47 CST 2022
     */
    private Integer his;
    private Integer finish;

    public Integer getFinish() {
        return finish;
    }
    public void setFinish(Integer finish){
        this.finish=finish;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HISTORY.USERNAME
     *
     * @return the value of HISTORY.USERNAME
     *
     * @mbg.generated Tue Jan 25 16:23:47 CST 2022
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HISTORY.USERNAME
     *
     * @param username the value for HISTORY.USERNAME
     *
     * @mbg.generated Tue Jan 25 16:23:47 CST 2022
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HISTORY.VIDEOID
     *
     * @return the value of HISTORY.VIDEOID
     *
     * @mbg.generated Tue Jan 25 16:23:47 CST 2022
     */
    public Integer getVideoid() {
        return videoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HISTORY.VIDEOID
     *
     * @param videoid the value for HISTORY.VIDEOID
     *
     * @mbg.generated Tue Jan 25 16:23:47 CST 2022
     */
    public void setVideoid(Integer videoid) {
        this.videoid = videoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HISTORY.TIME
     *
     * @return the value of HISTORY.TIME
     *
     * @mbg.generated Tue Jan 25 16:23:47 CST 2022
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HISTORY.TIME
     *
     * @param time the value for HISTORY.TIME
     *
     * @mbg.generated Tue Jan 25 16:23:47 CST 2022
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column HISTORY.HIS
     *
     * @return the value of HISTORY.HIS
     *
     * @mbg.generated Tue Jan 25 16:23:47 CST 2022
     */
    public Integer getHis() {
        return his;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column HISTORY.HIS
     *
     * @param his the value for HISTORY.HIS
     *
     * @mbg.generated Tue Jan 25 16:23:47 CST 2022
     */
    public void setHis(Integer his) {
        this.his = his;
    }
}